monolog:
    handlers:
        main:
            type: stream
            path: "php://stderr"
            level: info
            channels: ["!event", "!doctrine", "!security"]
            formatter: 'monolog.formatter.json'
        # so that we see the SQL request
        doctrine:
            type: stream
            path: "php://stderr"
            level: debug
            channels: ["doctrine"]
            formatter: 'monolog.formatter.json'
        console:
            type: stream
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
            path: "php://stderr"
